services:
  _defaults:
    autoconfigure: true
    autowire: true

  # Manager
  api_platform_user_security.password_change.manager:
    class: Dotsafe\ApiPlatformUserSecurityBundle\Manager\PasswordChangeManager
    autowire: true
    autoconfigure: true

  # Controller
  api_platform_user_security.password_change.controller:
    class: 'Dotsafe\ApiPlatformUserSecurityBundle\Controller\PasswordChangeController'
    arguments:
      $manager: '@api_platform_user_security.password_change.manager'
    tags:
      - {name: controller.service_arguments}

  # Validator
  api_platform_user_security.password_change.validator:
    class: Dotsafe\ApiPlatformUserSecurityBundle\Validator\Constraints\CurrentUserPasswordValidator
    autowire: true
    autoconfigure: true
    tags:
      - {name: validator.constraint_validator}
