version: "3.4"

services:
  php7.1:
    build:
      context: .
      args:
        PHP_VERSION: 7.1
        XDEBUG_VERSION: 2.9.8
    volumes:
      - ./..:/code
    tty: true

  php7.2:
    build:
      context: .
      args:
        PHP_VERSION: 7.2
        XDEBUG_VERSION: 3.0.4
    volumes:
      - ./..:/code
    tty: true

  php7.3:
    build:
      context: .
      args:
        PHP_VERSION: 7.3
        XDEBUG_VERSION: 3.0.4
    volumes:
      - ./..:/code
    tty: true

  php7.4:
    build:
      context: .
      args:
        PHP_VERSION: 7.4
        XDEBUG_VERSION: 3.0.4
    volumes:
      - ./..:/code
    tty: true

  php8.0:
    build:
      context: .
      args:
        PHP_VERSION: 8.0
        XDEBUG_VERSION: 3.0.4
    volumes:
      - ./..:/code
    tty: true
