resources:
  Dotsafe\ApiPlatformUserSecurityBundle\Dto\PasswordChange:
    shortName: "UserSecurityPasswordChange"
    collectionOperations:
      post:
        path: '%api_platform_user_security.password_change_path%'
        controller: 'api_platform_user_security.password_change.controller'
        security: "is_granted('ROLE_USER')"
        openapi_context:
          summary: "Reset the password"
          description: |
            This endpoint must be used to change the logged user password.
          requestBody:
            content:
              "*/*":
                schema:
                  type: object
                  properties:
                    currentPassword: {type: string}
                    plainPassword: {type: string}
                    plainPasswordConfirmation: {type: string}
          responses:
            204:
              description: "The request has been processed."
            400:
              description: "The current password does not match or the new password and its confirmation mismatch."
    itemOperations: []